### PR TITLE
Upgrading to Laravel 5.7

### PR DESCRIPTION
**Pull request by palypster**
Not finished, one tests is failing when run together with all the other tests, but pass if run separately. 

```
± % ./vendor/bin/phpunit --filter reset_password_after_form_filled                                                                                                                                                                      !3206
PHPUnit 7.4.3 by Sebastian Bergmann and contributors.

E                                                                   1 / 1 (100%)

Time: 139 ms, Memory: 16.00MB

There was 1 error:

1) Brackets\AdminAuth\Tests\Auth\ResetPasswordTest::reset_password_after_form_filled
ErrorException: Illegal offset type in isset or empty

/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Support/NamespacedItemResolver.php:25
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Translation/Translator.php:373
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Translation/Translator.php:115
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Translation/Translator.php:101
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:914
/Users/palino/Code/c57/vendor/brackets/admin-auth/src/Http/Controllers/Auth/ResetPasswordController.php:88
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Auth/ResetsPasswords.php:55
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Route.php:212
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Route.php:169
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Router.php:679
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/orchestra/testbench-core/src/Http/Middleware/RedirectIfAuthenticated.php:25
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Router.php:681
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Router.php:656
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Router.php:622
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Router.php:611
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:345
/Users/palino/Code/c57/vendor/brackets/admin-auth/vendor/laravel/framework/src/Illuminate/Foundation/Testing/Concerns/MakesHttpRequests.php:195
/Users/palino/Code/c57/vendor/brackets/admin-auth/tests/Feature/Password/ResetPasswordTest.php:69

ERRORS!
Tests: 1, Assertions: 2, Errors: 1.

```

@dejwCake any idea where do I start digging?

### CODE REVIEW

**Comment by palypster** [comment]
Okay, it's probably done. But it turned out that this is backward incompatible, so we need to update major version. Probably no need for Craftable 3 still. Need further investigation. Think also about existing projects.

**Comment by dejwCake** [comment]
Yes, this is not backward compatible, so I do not recommend this approach.

**Comment by palypster** [comment]
Let's wait if we accept #9 and then let's get back to this one.

**Review by dejwCake — APPROVED** [review]
Great work!

**Pull request merged**
